/**
 * Health Alerts
 * This application allows users to send and receive information about a user's health condition.
 *
 * OpenAPI spec version: 1.0
 * Contact: info@spilab.es
 *
 * NOTE: This class is auto generated by OpenAPI-Generator unset.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Event.h"

namespace org {
namespace openapitools {
namespace server {
namespace src {
namespace models {

//Constructors
Event::Event()
{
    id = 0L;
    title = "";
    description = "";
    location = Location();
}
Event::Event(long _id, const char* _title, const char* _description, const Location _location)
{
    id = _id;
    title = _title;
    description = _description;
    location = _location;
}

// Setters & Getters
long Event::getId()
{
    return id;
}

void Event::setId(long value)
{
    id = value;
}

const char* Event::getTitle()
{
    return title;
}

void Event::setTitle(const char* value)
{
    title = value;
}

const char* Event::getDescription()
{
    return description;
}

void Event::setDescription(const char* value)
{
    description = value;
}

Location Event::getLocation()
{
    return location;
}

void Event::setLocation(Location value)
{
    location = value;
}


}
}
}
}
}

