/**
 * Health Alerts
 * This application allows users to send and receive information about a user's health condition.
 *
 * OpenAPI spec version: 1.0
 * Contact: info@spilab.es
 *
 * NOTE: This class is auto generated by OpenAPI-Generator unset.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Event.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_SERVER_SRC_MODELS_Event_H_
#define ORG_OPENAPITOOLS_SERVER_SRC_MODELS_Event_H_

#include <Arduino.h>
#include "Location.h"


namespace org {
namespace openapitools {
namespace server {
namespace src {
namespace models {

/// <summary>
/// 
/// </summary>
class  Event {
    // Properties
    long id;
    const char* title;
    const char* description;
    Location location;

    public:
        // Constructor
        Event();
        Event( long _id,  const char* _title,  const char* _description, const Location _location);

        /////////////////////////////////////////////
        /// Event members

        /// <summary>
        /// 
        /// </summary>
        long getId();
        void setId(long value);

        /// <summary>
        /// 
        /// </summary>
        const char* getTitle();
        void setTitle(const char* value);

        /// <summary>
        /// 
        /// </summary>
        const char* getDescription();
        void setDescription(const char* value);

        /// <summary>
        /// 
        /// </summary>
        Location getLocation();
        void setLocation(Location value);


};

}
}
}
}
}

#endif /* ORG_OPENAPITOOLS_SERVER_SRC_MODELS_Event_H_ */
