/**
 * Health Alerts
 * This application allows users to send and receive information about a user's health condition.
 *
 * OpenAPI spec version: 1.0
 * Contact: info@spilab.es
 *
 * NOTE: This class is auto generated by OpenAPI-Generator unset.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * User.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_SERVER_SRC_MODELS_User_H_
#define ORG_OPENAPITOOLS_SERVER_SRC_MODELS_User_H_

#include <Arduino.h>


namespace org {
namespace openapitools {
namespace server {
namespace src {
namespace models {

/// <summary>
/// 
/// </summary>
class  User {
    // Properties
    const char* id;
    const char* details;

    public:
        // Constructor
        User();
        User( const char* _id,  const char* _details);

        /////////////////////////////////////////////
        /// User members

        /// <summary>
        /// 
        /// </summary>
        const char* getId();
        void setId(const char* value);

        /// <summary>
        /// 
        /// </summary>
        const char* getDetails();
        void setDetails(const char* value);


};

}
}
}
}
}

#endif /* ORG_OPENAPITOOLS_SERVER_SRC_MODELS_User_H_ */
