/**
 * Health Alerts
 * This application allows users to send and receive information about a user's health condition.
 *
 * OpenAPI spec version: 1.0
 * Contact: info@spilab.es
 *
 * NOTE: This class is auto generated by OpenAPI-Generator unset.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "User.h"

namespace org {
namespace openapitools {
namespace server {
namespace src {
namespace models {

//Constructors
User::User()
{
    id = "";
    details = "";
}
User::User(const char* _id, const char* _details)
{
    id = _id;
    details = _details;
}

// Setters & Getters
const char* User::getId()
{
    return id;
}

void User::setId(const char* value)
{
    id = value;
}

const char* User::getDetails()
{
    return details;
}

void User::setDetails(const char* value)
{
    details = value;
}


}
}
}
}
}

