/**
 * Health Alerts
 * This application allows users to send and receive information about a user's health condition.
 *
 * OpenAPI spec version: 1.0
 * Contact: info@spilab.es
 *
 * NOTE: This class is auto generated by OpenAPI-Generator unset.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "EventResource.h"



namespace org {
namespace openapitools {
namespace server {
namespace src {
namespace resources {

using namespace org::openapitools::server::src::models;

    EventResource::EventResource(MqttService *_mqttService) {
        mqttService = _mqttService;
    };

    void EventResource::postEvent (Event &_event, int &sender) {
        // TODO Mocked response
        Serial.println("Method: postEvent");
        mqttService->sendResponse("mytopic/testResponse","201 Succesful response");
        // additional response of type const char* :     mqttService->sendResponse("mytopic/testResponse","404 Not found response");
    }

    void EventResource::sendAlert () {

    	// Creates a new location
    	Location loc = Location(39.47903,-6.342139,20);
	    // Creates a new event
	    Event alert = Event(1,"Need help!","I have fallen",loc);
	    // Sends the event/alert
	    mqttService->sendResponse("mytopic/testResponse", (char*) JsonUtil::serializeEvent(alert));
	}

}
}
}
}
}

