/**
 * Health Alerts
 * This application allows users to send and receive information about a user's health condition.
 *
 * OpenAPI spec version: 1.0
 * Contact: info@spilab.es
 *
 * NOTE: This class is auto generated by OpenAPI-Generator unset.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EventResource.h
 *
 * 
 */

#ifndef EventResource_H_
#define EventResource_H_

// import models
#include "../models/Event.h"

// import services
#include "../services/MqttService.h"

// import utils
#include "../utils/JsonUtil.h"

namespace org {
namespace openapitools {
namespace server {
namespace src {
namespace resources {

using namespace org::openapitools::server::src::models;

class EventResource {

    MqttService *mqttService;
    char* topicResponse = "HealthAlertsAndroid";

public:
    EventResource(MqttService *_mqttService);

    void postEvent (Event &_event, int &sender);
    
    void sendAlert ();

};

}
}
}
}
}

#endif /* EventResource_H_ */

