/**
 * Health Alerts
 * This application allows users to send and receive information about a user's health condition.
 *
 * OpenAPI spec version: 1.0
 * Contact: info@spilab.es
 *
 * NOTE: This class is auto generated by OpenAPI-Generator unset.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/*
MQTT Service wrapper.
Header file.
*/

#ifndef MQTTSERVICE_H_
#define MQTTSERVICE_H_

#include <Arduino.h>
#include <ArduinoJson.h>
#include <PubSubClient.h>

class MqttService {
    // Properties:
    PubSubClient *clientPtr;

    public:
        MqttService(PubSubClient* _clientPtr);

        // Methods
        void sendResponse(char* topic, char* payload);

};

#endif /* MQTTSERVICE_H_ */