/**
 * Health Alerts
 * This application allows users to send and receive information about a user's health condition.
 *
 * OpenAPI spec version: 1.0
 * Contact: info@spilab.es
 *
 * NOTE: This class is auto generated by OpenAPI-Generator unset.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/*
MQTT Service wrapper
Source file.
*/

#include "MqttService.h"

MqttService::MqttService(PubSubClient* _clientPtr){
    clientPtr = _clientPtr;
}

void MqttService::sendResponse(char* topic, char* payload) {
    if(clientPtr->publish(topic, payload,true)==true){
        Serial.println("Publish succeeded");
    }else{
        Serial.println("Publish failed");
    }
}